#!/bin/sh

case "$(printf "%s\n" "$1" | awk '{print tolower($0)}')" in
*.tgz | *.tar | *.zip | *.7z | *.gz | *.xz | *.lzma | *.bz | *.bz2 | *.bz3 | *.lz4 | *.sz | *.zst | *.rar | *.br) ouch l "$1" ;;
*.[1-8]) man "$1" | col -b ;;
*.o) nm "$1" ;;
*) bat --color=always --style=plain --pager=never "$1" ;;
esac
exit 0
